# Generated by Django 5.2.4 on 2025-08-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_profile_birthdate_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(choices=[('Planting', 'Tree Planting & Greening'), ('Cleaning', 'Clean-Up Drives'), ('Teaching', 'Community Teaching'), ('HealthCamp', 'Health Camps'), ('WasteMgmt', 'Waste Management'), ('WaterConservation', 'Water Conservation'), ('Advocacy', 'Advocacy & Awareness'), ('Other', 'Other')], max_length=50),
        ),
    ]
