# Generated by Django 5.2.4 on 2025-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profile_birthday_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(choices=[('Planting', 'Tree Planting & Greening'), ('Cleaning', 'Clean-Up Drives'), ('Teaching', 'Community Teaching'), ('AnimalCare', 'Animal Welfare'), ('HealthCamp', 'Health Camps'), ('WasteMgmt', 'Waste Management'), ('WaterConservation', 'Water Conservation'), ('DisasterRelief', 'Disaster Relief'), ('ElderCare', 'Support for Elderly'), ('ChildWelfare', 'Child Welfare'), ('Fundraising', 'Fundraising'), ('Advocacy', 'Advocacy & Awareness'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
