# Generated by Django 5.2.4 on 2025-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_date_donation_created_at_donation_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntear',
            name='interest',
            field=models.CharField(choices=[('Planting', 'Tree Planting & Greening'), ('Cleaning', 'Clean-Up Drives'), ('Teaching', 'Community Teaching'), ('AnimalCare', 'Animal Welfare'), ('HealthCamp', 'Health Camps'), ('WasteMgmt', 'Waste Management'), ('WaterConservation', 'Water Conservation'), ('DisasterRelief', 'Disaster Relief'), ('ElderCare', 'Support for Elderly'), ('ChildWelfare', 'Child Welfare'), ('Fundraising', 'Fundraising'), ('Advocacy', 'Advocacy & Awareness'), ('Other', 'Other')], max_length=50),
        ),
    ]
