# Generated by Django 5.2.4 on 2025-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_voluntear_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Green Horizon Assistant', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('welcome_message', models.TextField(default="Hello! I'm your Green Horizon assistant. How can I help you today?")),
            ],
        ),
    ]
