# Generated by Django 5.2.4 on 2025-08-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_aiassistant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voluntear',
            new_name='Volunteer',
        ),
        migrations.DeleteModel(
            name='AIAssistant',
        ),
    ]
